//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.261
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentIt
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaInfo", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.AlbumInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.SongInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.MovieInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.BookInfo))]
    public partial class MediaInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GenreField;
        
        private int IdField;
        
        private int PriceField;
        
        private string PublisherField;
        
        private RentIt.MediaRating RatingField;
        
        private System.DateTime ReleaseDateField;
        
        private string TitleField;
        
        private RentIt.MediaType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this.GenreField;
            }
            set
            {
                this.GenreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaRating Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate
        {
            get
            {
                return this.ReleaseDateField;
            }
            set
            {
                this.ReleaseDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaRating", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class MediaRating : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float AverageRatingField;
        
        private int RatingsCountField;
        
        private RentIt.MediaReview[] ReviewsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float AverageRating
        {
            get
            {
                return this.AverageRatingField;
            }
            set
            {
                this.AverageRatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingsCount
        {
            get
            {
                return this.RatingsCountField;
            }
            set
            {
                this.RatingsCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaReview[] Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlbumInfo", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class AlbumInfo : RentIt.MediaInfo
    {
        
        private string AlbumArtistField;
        
        private string DescriptionField;
        
        private RentIt.SongInfo[] SongsField;
        
        private System.TimeSpan TotalDurationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlbumArtist
        {
            get
            {
                return this.AlbumArtistField;
            }
            set
            {
                this.AlbumArtistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.SongInfo[] Songs
        {
            get
            {
                return this.SongsField;
            }
            set
            {
                this.SongsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TotalDuration
        {
            get
            {
                return this.TotalDurationField;
            }
            set
            {
                this.TotalDurationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongInfo", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class SongInfo : RentIt.MediaInfo
    {
        
        private int AlbumIdField;
        
        private string ArtistField;
        
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlbumId
        {
            get
            {
                return this.AlbumIdField;
            }
            set
            {
                this.AlbumIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist
        {
            get
            {
                return this.ArtistField;
            }
            set
            {
                this.ArtistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieInfo", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class MovieInfo : RentIt.MediaInfo
    {
        
        private string DirectorField;
        
        private System.TimeSpan DurationField;
        
        private string SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Director
        {
            get
            {
                return this.DirectorField;
            }
            set
            {
                this.DirectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInfo", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class BookInfo : RentIt.MediaInfo
    {
        
        private string AuthorField;
        
        private int PagesField;
        
        private string SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pages
        {
            get
            {
                return this.PagesField;
            }
            set
            {
                this.PagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaType", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public enum MediaType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Any = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Book = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Movie = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Album = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Song = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaReview", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial struct MediaReview : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MediaIdField;
        
        private RentIt.Rating RatingField;
        
        private string ReviewTextField;
        
        private System.DateTime TimestampField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaId
        {
            get
            {
                return this.MediaIdField;
            }
            set
            {
                this.MediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.Rating Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewText
        {
            get
            {
                return this.ReviewTextField;
            }
            set
            {
                this.ReviewTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public enum Rating : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        One = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Two = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Four = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Five = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaCriteria", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class MediaCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GenreField;
        
        private int LimitField;
        
        private int OffsetField;
        
        private RentIt.MediaOrder OrderField;
        
        private string SearchTextField;
        
        private RentIt.MediaType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this.GenreField;
            }
            set
            {
                this.GenreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Offset
        {
            get
            {
                return this.OffsetField;
            }
            set
            {
                this.OffsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaOrder Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchText
        {
            get
            {
                return this.SearchTextField;
            }
            set
            {
                this.SearchTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaOrder", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public enum MediaOrder : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReleaseDateAsc = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReleaseDateDesc = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RatingAsc = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RatingDesc = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PopularityAsc = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PopularityDesc = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlphabeticalAsc = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlphabeticalDesc = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PriceAsc = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PriceDesc = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaItems", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class MediaItems : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private RentIt.AlbumInfo[] AlbumsField;
        
        private RentIt.BookInfo[] BooksField;
        
        private RentIt.MovieInfo[] MoviesField;
        
        private RentIt.SongInfo[] SongsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.AlbumInfo[] Albums
        {
            get
            {
                return this.AlbumsField;
            }
            set
            {
                this.AlbumsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.BookInfo[] Books
        {
            get
            {
                return this.BooksField;
            }
            set
            {
                this.BooksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MovieInfo[] Movies
        {
            get
            {
                return this.MoviesField;
            }
            set
            {
                this.MoviesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.SongInfo[] Songs
        {
            get
            {
                return this.SongsField;
            }
            set
            {
                this.SongsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountCredentials", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class AccountCredentials : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string HashedPasswordField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashedPassword
        {
            get
            {
                return this.HashedPasswordField;
            }
            set
            {
                this.HashedPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.UserAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentIt.PublisherAccount))]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string FullNameField;
        
        private string HashedPasswordField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashedPassword
        {
            get
            {
                return this.HashedPasswordField;
            }
            set
            {
                this.HashedPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class UserAccount : RentIt.Account
    {
        
        private int CreditsField;
        
        private RentIt.Rental[] RentalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Credits
        {
            get
            {
                return this.CreditsField;
            }
            set
            {
                this.CreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.Rental[] Rentals
        {
            get
            {
                return this.RentalsField;
            }
            set
            {
                this.RentalsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublisherAccount", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial class PublisherAccount : RentIt.Account
    {
        
        private RentIt.MediaItems PublishedItemsField;
        
        private string PublisherNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaItems PublishedItems
        {
            get
            {
                return this.PublishedItemsField;
            }
            set
            {
                this.PublishedItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublisherName
        {
            get
            {
                return this.PublisherNameField;
            }
            set
            {
                this.PublisherNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rental", Namespace="http://schemas.datacontract.org/2004/07/RentIt")]
    public partial struct Rental : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime EndTimeField;
        
        private int MediaIdField;
        
        private RentIt.MediaType MediaTypeField;
        
        private System.DateTime StartTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaId
        {
            get
            {
                return this.MediaIdField;
            }
            set
            {
                this.MediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentIt.MediaType MediaType
        {
            get
            {
                return this.MediaTypeField;
            }
            set
            {
                this.MediaTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
}
namespace System.ServiceModel
{
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0 : System.ServiceModel.FaultException
    {
        
        public FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class FaultExceptionOfUserCreationExceptionFe9b7uG0 : System.ServiceModel.FaultException
    {
        
        public FaultExceptionOfUserCreationExceptionFe9b7uG0(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRentIt")]
public interface IRentIt
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetBookInfo", ReplyAction="http://tempuri.org/IRentIt/GetBookInfoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetBookInfoFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetBookInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.BookInfo GetBookInfo(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetMovieInfo", ReplyAction="http://tempuri.org/IRentIt/GetMovieInfoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetMovieInfoFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetMovieInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.MovieInfo GetMovieInfo(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAlbumInfo", ReplyAction="http://tempuri.org/IRentIt/GetAlbumInfoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAlbumInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAlbumInfoFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.AlbumInfo GetAlbumInfo(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetMediaItems", ReplyAction="http://tempuri.org/IRentIt/GetMediaItemsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetMediaItemsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetMediaItemsFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.MediaItems GetMediaItems(RentIt.MediaCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAlsoRentedItems", ReplyAction="http://tempuri.org/IRentIt/GetAlsoRentedItemsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAlsoRentedItemsFaultExceptionOf_ArgumentExceptionFa" +
        "ult", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAlsoRentedItemsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.MediaItems GetAlsoRentedItems(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/ValidateCredentials", ReplyAction="http://tempuri.org/IRentIt/ValidateCredentialsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/ValidateCredentialsFaultExceptionOf_InvalidCredentials" +
        "ExceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/ValidateCredentialsFaultExceptionOf_ArgumentExceptionF" +
        "ault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/ValidateCredentialsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.Account ValidateCredentials(RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/CreateNewUser", ReplyAction="http://tempuri.org/IRentIt/CreateNewUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfUserCreationExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/CreateNewUserFaultExceptionOf_UserCreationExceptionFau" +
        "lt", Name="FaultExceptionOfUserCreationExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/CreateNewUserFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/CreateNewUserFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool CreateNewUser(RentIt.Account newAccount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAllCustomerData", ReplyAction="http://tempuri.org/IRentIt/GetAllCustomerDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAllCustomerDataFaultExceptionOf_ArgumentExceptionFa" +
        "ult", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAllCustomerDataFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/GetAllCustomerDataFaultExceptionOf_InvalidCredentialsE" +
        "xceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.UserAccount GetAllCustomerData(RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAllPublisherData", ReplyAction="http://tempuri.org/IRentIt/GetAllPublisherDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAllPublisherDataFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/GetAllPublisherDataFaultExceptionOf_InvalidCredentials" +
        "ExceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAllPublisherDataFaultExceptionOf_ArgumentExceptionF" +
        "ault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    RentIt.PublisherAccount GetAllPublisherData(RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/UpdateAccountInfo", ReplyAction="http://tempuri.org/IRentIt/UpdateAccountInfoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/UpdateAccountInfoFaultExceptionOf_InvalidCredentialsEx" +
        "ceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/UpdateAccountInfoFaultExceptionOf_ArgumentExceptionFau" +
        "lt", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/UpdateAccountInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool UpdateAccountInfo(RentIt.AccountCredentials credentials, RentIt.Account account);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/AddCredits", ReplyAction="http://tempuri.org/IRentIt/AddCreditsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/AddCreditsFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/AddCreditsFaultExceptionOf_InvalidCredentialsException" +
        "Fault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/AddCreditsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool AddCredits(RentIt.AccountCredentials credentials, uint addAmount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/RentMedia", ReplyAction="http://tempuri.org/IRentIt/RentMediaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/RentMediaFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/RentMediaFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/RentMediaFaultExceptionOf_InvalidCredentialsExceptionF" +
        "ault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool RentMedia(int mediaId, RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/PublishMedia", ReplyAction="http://tempuri.org/IRentIt/PublishMediaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/PublishMediaFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/PublishMediaFaultExceptionOf_InvalidCredentialsExcepti" +
        "onFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/PublishMediaFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    int PublishMedia(RentIt.MediaInfo info, RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/DeleteAccount", ReplyAction="http://tempuri.org/IRentIt/DeleteAccountResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/DeleteAccountFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/DeleteAccountFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/DeleteAccountFaultExceptionOf_InvalidCredentialsExcept" +
        "ionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool DeleteAccount(RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/UpdateMediaMetadata", ReplyAction="http://tempuri.org/IRentIt/UpdateMediaMetadataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/UpdateMediaMetadataFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/UpdateMediaMetadataFaultExceptionOf_InvalidCredentials" +
        "ExceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/UpdateMediaMetadataFaultExceptionOf_ArgumentExceptionF" +
        "ault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool UpdateMediaMetadata(RentIt.MediaInfo newData, RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/DeleteMedia", ReplyAction="http://tempuri.org/IRentIt/DeleteMediaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/DeleteMediaFaultExceptionOf_InvalidCredentialsExceptio" +
        "nFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/DeleteMediaFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/DeleteMediaFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool DeleteMedia(int mediaId, RentIt.AccountCredentials credentials);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAllGenres", ReplyAction="http://tempuri.org/IRentIt/GetAllGenresResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IRentIt/GetAllGenresExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
    string[] GetAllGenres(RentIt.MediaType mediaType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/SubmitReview", ReplyAction="http://tempuri.org/IRentIt/SubmitReviewResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/SubmitReviewFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/SubmitReviewFaultExceptionOf_InvalidCredentialsExcepti" +
        "onFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/SubmitReviewFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    bool SubmitReview(RentIt.MediaReview review, RentIt.AccountCredentials credentials);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRentItChannel : IRentIt, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RentItClient : System.ServiceModel.ClientBase<IRentIt>, IRentIt
{
    
    public RentItClient()
    {
    }
    
    public RentItClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RentItClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RentItClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RentItClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public RentIt.BookInfo GetBookInfo(int id)
    {
        return base.Channel.GetBookInfo(id);
    }
    
    public RentIt.MovieInfo GetMovieInfo(int id)
    {
        return base.Channel.GetMovieInfo(id);
    }
    
    public RentIt.AlbumInfo GetAlbumInfo(int id)
    {
        return base.Channel.GetAlbumInfo(id);
    }
    
    public RentIt.MediaItems GetMediaItems(RentIt.MediaCriteria criteria)
    {
        return base.Channel.GetMediaItems(criteria);
    }
    
    public RentIt.MediaItems GetAlsoRentedItems(int id)
    {
        return base.Channel.GetAlsoRentedItems(id);
    }
    
    public RentIt.Account ValidateCredentials(RentIt.AccountCredentials credentials)
    {
        return base.Channel.ValidateCredentials(credentials);
    }
    
    public bool CreateNewUser(RentIt.Account newAccount)
    {
        return base.Channel.CreateNewUser(newAccount);
    }
    
    public RentIt.UserAccount GetAllCustomerData(RentIt.AccountCredentials credentials)
    {
        return base.Channel.GetAllCustomerData(credentials);
    }
    
    public RentIt.PublisherAccount GetAllPublisherData(RentIt.AccountCredentials credentials)
    {
        return base.Channel.GetAllPublisherData(credentials);
    }
    
    public bool UpdateAccountInfo(RentIt.AccountCredentials credentials, RentIt.Account account)
    {
        return base.Channel.UpdateAccountInfo(credentials, account);
    }
    
    public bool AddCredits(RentIt.AccountCredentials credentials, uint addAmount)
    {
        return base.Channel.AddCredits(credentials, addAmount);
    }
    
    public bool RentMedia(int mediaId, RentIt.AccountCredentials credentials)
    {
        return base.Channel.RentMedia(mediaId, credentials);
    }
    
    public int PublishMedia(RentIt.MediaInfo info, RentIt.AccountCredentials credentials)
    {
        return base.Channel.PublishMedia(info, credentials);
    }
    
    public bool DeleteAccount(RentIt.AccountCredentials credentials)
    {
        return base.Channel.DeleteAccount(credentials);
    }
    
    public bool UpdateMediaMetadata(RentIt.MediaInfo newData, RentIt.AccountCredentials credentials)
    {
        return base.Channel.UpdateMediaMetadata(newData, credentials);
    }
    
    public bool DeleteMedia(int mediaId, RentIt.AccountCredentials credentials)
    {
        return base.Channel.DeleteMedia(mediaId, credentials);
    }
    
    public string[] GetAllGenres(RentIt.MediaType mediaType)
    {
        return base.Channel.GetAllGenres(mediaType);
    }
    
    public bool SubmitReview(RentIt.MediaReview review, RentIt.AccountCredentials credentials)
    {
        return base.Channel.SubmitReview(review, credentials);
    }
}
