//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientControlLibrary.RentItServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentItServiceReference.IRentIt")]
    internal interface IRentIt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetBookInfo", ReplyAction="http://tempuri.org/IRentIt/GetBookInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetBookInfoFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetBookInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.BookInfo GetBookInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetMovieInfo", ReplyAction="http://tempuri.org/IRentIt/GetMovieInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetMovieInfoFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetMovieInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.MovieInfo GetMovieInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAlbumInfo", ReplyAction="http://tempuri.org/IRentIt/GetAlbumInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAlbumInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAlbumInfoFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.AlbumInfo GetAlbumInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetMediaItems", ReplyAction="http://tempuri.org/IRentIt/GetMediaItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetMediaItemsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetMediaItemsFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.MediaItems GetMediaItems(RentIt.MediaCriteria criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAlsoRentedItems", ReplyAction="http://tempuri.org/IRentIt/GetAlsoRentedItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAlsoRentedItemsFaultExceptionOf_ArgumentExceptionFa" +
            "ult", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAlsoRentedItemsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.MediaItems GetAlsoRentedItems(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/ValidateCredentials", ReplyAction="http://tempuri.org/IRentIt/ValidateCredentialsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/ValidateCredentialsFaultExceptionOf_InvalidCredentials" +
            "ExceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/ValidateCredentialsFaultExceptionOf_ArgumentExceptionF" +
            "ault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/ValidateCredentialsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.UserAccount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.PublisherAccount))]
        RentIt.Account ValidateCredentials(RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/CreateNewUser", ReplyAction="http://tempuri.org/IRentIt/CreateNewUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfUserCreationExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/CreateNewUserFaultExceptionOf_UserCreationExceptionFau" +
            "lt", Name="FaultExceptionOfUserCreationExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/CreateNewUserFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/CreateNewUserFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.UserAccount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.PublisherAccount))]
        bool CreateNewUser(RentIt.Account newAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAllCustomerData", ReplyAction="http://tempuri.org/IRentIt/GetAllCustomerDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAllCustomerDataFaultExceptionOf_ArgumentExceptionFa" +
            "ult", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAllCustomerDataFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/GetAllCustomerDataFaultExceptionOf_InvalidCredentialsE" +
            "xceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.UserAccount GetAllCustomerData(RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAllPublisherData", ReplyAction="http://tempuri.org/IRentIt/GetAllPublisherDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/GetAllPublisherDataFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/GetAllPublisherDataFaultExceptionOf_InvalidCredentials" +
            "ExceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/GetAllPublisherDataFaultExceptionOf_ArgumentExceptionF" +
            "ault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        RentIt.PublisherAccount GetAllPublisherData(RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/UpdateAccountInfo", ReplyAction="http://tempuri.org/IRentIt/UpdateAccountInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/UpdateAccountInfoFaultExceptionOf_InvalidCredentialsEx" +
            "ceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/UpdateAccountInfoFaultExceptionOf_ArgumentExceptionFau" +
            "lt", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/UpdateAccountInfoFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.UserAccount))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.PublisherAccount))]
        bool UpdateAccountInfo(RentIt.AccountCredentials credentials, RentIt.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/AddCredits", ReplyAction="http://tempuri.org/IRentIt/AddCreditsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/AddCreditsFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/AddCreditsFaultExceptionOf_InvalidCredentialsException" +
            "Fault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/AddCreditsFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        bool AddCredits(RentIt.AccountCredentials credentials, uint addAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/RentMedia", ReplyAction="http://tempuri.org/IRentIt/RentMediaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/RentMediaFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/RentMediaFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/RentMediaFaultExceptionOf_InvalidCredentialsExceptionF" +
            "ault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        bool RentMedia(int mediaId, RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/PublishMedia", ReplyAction="http://tempuri.org/IRentIt/PublishMediaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/PublishMediaFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/PublishMediaFaultExceptionOf_InvalidCredentialsExcepti" +
            "onFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/PublishMediaFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.AlbumInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.SongInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.MovieInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.BookInfo))]
        int PublishMedia(RentIt.MediaInfo info, RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/DeleteAccount", ReplyAction="http://tempuri.org/IRentIt/DeleteAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/DeleteAccountFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/DeleteAccountFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/DeleteAccountFaultExceptionOf_InvalidCredentialsExcept" +
            "ionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        bool DeleteAccount(RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/UpdateMediaMetadata", ReplyAction="http://tempuri.org/IRentIt/UpdateMediaMetadataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/UpdateMediaMetadataFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/UpdateMediaMetadataFaultExceptionOf_InvalidCredentials" +
            "ExceptionFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/UpdateMediaMetadataFaultExceptionOf_ArgumentExceptionF" +
            "ault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.AlbumInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.SongInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.MovieInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RentIt.BookInfo))]
        bool UpdateMediaMetadata(RentIt.MediaInfo newData, RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/DeleteMedia", ReplyAction="http://tempuri.org/IRentIt/DeleteMediaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/DeleteMediaFaultExceptionOf_InvalidCredentialsExceptio" +
            "nFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/DeleteMediaFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/DeleteMediaFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        bool DeleteMedia(int mediaId, RentIt.AccountCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/GetAllGenres", ReplyAction="http://tempuri.org/IRentIt/GetAllGenresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IRentIt/GetAllGenresExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        string[] GetAllGenres(RentIt.MediaType mediaType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentIt/SubmitReview", ReplyAction="http://tempuri.org/IRentIt/SubmitReviewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.Exception>), Action="http://tempuri.org/IRentIt/SubmitReviewFaultExceptionOf_ExceptionFault", Name="FaultExceptionOfException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0), Action="http://tempuri.org/IRentIt/SubmitReviewFaultExceptionOf_InvalidCredentialsExcepti" +
            "onFault", Name="FaultExceptionOfInvalidCredentialsExceptionFe9b7uG0", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException<System.ArgumentException>), Action="http://tempuri.org/IRentIt/SubmitReviewFaultExceptionOf_ArgumentExceptionFault", Name="FaultExceptionOfArgumentException5F2dSckg", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        bool SubmitReview(RentIt.MediaReview review, RentIt.AccountCredentials credentials);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IRentItChannel : ClientControlLibrary.RentItServiceReference.IRentIt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class RentItClient : System.ServiceModel.ClientBase<ClientControlLibrary.RentItServiceReference.IRentIt>, ClientControlLibrary.RentItServiceReference.IRentIt {
        
        public RentItClient() {
        }
        
        public RentItClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentItClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentItClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentItClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RentIt.BookInfo GetBookInfo(int id) {
            return base.Channel.GetBookInfo(id);
        }
        
        public RentIt.MovieInfo GetMovieInfo(int id) {
            return base.Channel.GetMovieInfo(id);
        }
        
        public RentIt.AlbumInfo GetAlbumInfo(int id) {
            return base.Channel.GetAlbumInfo(id);
        }
        
        public RentIt.MediaItems GetMediaItems(RentIt.MediaCriteria criteria) {
            return base.Channel.GetMediaItems(criteria);
        }
        
        public RentIt.MediaItems GetAlsoRentedItems(int id) {
            return base.Channel.GetAlsoRentedItems(id);
        }
        
        public RentIt.Account ValidateCredentials(RentIt.AccountCredentials credentials) {
            return base.Channel.ValidateCredentials(credentials);
        }
        
        public bool CreateNewUser(RentIt.Account newAccount) {
            return base.Channel.CreateNewUser(newAccount);
        }
        
        public RentIt.UserAccount GetAllCustomerData(RentIt.AccountCredentials credentials) {
            return base.Channel.GetAllCustomerData(credentials);
        }
        
        public RentIt.PublisherAccount GetAllPublisherData(RentIt.AccountCredentials credentials) {
            return base.Channel.GetAllPublisherData(credentials);
        }
        
        public bool UpdateAccountInfo(RentIt.AccountCredentials credentials, RentIt.Account account) {
            return base.Channel.UpdateAccountInfo(credentials, account);
        }
        
        public bool AddCredits(RentIt.AccountCredentials credentials, uint addAmount) {
            return base.Channel.AddCredits(credentials, addAmount);
        }
        
        public bool RentMedia(int mediaId, RentIt.AccountCredentials credentials) {
            return base.Channel.RentMedia(mediaId, credentials);
        }
        
        public int PublishMedia(RentIt.MediaInfo info, RentIt.AccountCredentials credentials) {
            return base.Channel.PublishMedia(info, credentials);
        }
        
        public bool DeleteAccount(RentIt.AccountCredentials credentials) {
            return base.Channel.DeleteAccount(credentials);
        }
        
        public bool UpdateMediaMetadata(RentIt.MediaInfo newData, RentIt.AccountCredentials credentials) {
            return base.Channel.UpdateMediaMetadata(newData, credentials);
        }
        
        public bool DeleteMedia(int mediaId, RentIt.AccountCredentials credentials) {
            return base.Channel.DeleteMedia(mediaId, credentials);
        }
        
        public string[] GetAllGenres(RentIt.MediaType mediaType) {
            return base.Channel.GetAllGenres(mediaType);
        }
        
        public bool SubmitReview(RentIt.MediaReview review, RentIt.AccountCredentials credentials) {
            return base.Channel.SubmitReview(review, credentials);
        }
    }
}
